### PR TITLE
Add go-readability

### PR DESCRIPTION
**Pull request by saippuakauppias**

### CODE REVIEW

**Comment by lopuhin** [comment]
Thanks @saippuakauppias , could you please trigger a re-build to check how it works after #7 was merged?

**Review by lopuhin — COMMENTED** [review]
Looks great, thanks @saippuakauppias . Could you please merge master in and resolve the conflict? Or if you don't mind I can resolve it in a branch.

**Comment by saippuakauppias** [comment]
Done :)

**Review by lopuhin — APPROVED** [review]
Great, thank you @saippuakauppias 👍

**Pull request merged**
