### PR TITLE
Add news-please

### PR DESCRIPTION
**Pull request by saippuakauppias**

### CODE REVIEW

**Review by lopuhin — APPROVED** [review]
Looks great, thanks @saippuakauppias

**Comment by lopuhin** [comment]
I resolved the conflict and merged in https://github.com/scrapinghub/article-extraction-benchmark/commit/cce282b45c3231a41f9816e7242bcbf1f53404bb - sorry I thought GH would mark this PR as merged

**Comment by saippuakauppias** [comment]
I think it's because I resolve conflicts too )))

**Comment by lopuhin** [comment]
Yep sorry about that!

**Pull request closed without merging**
