### PR TITLE
Added BeautifulSoup

### PR DESCRIPTION
**Pull request by ldulcic**

### CODE REVIEW

**Review by lopuhin — COMMENTED** [review]
Thanks @ldulcic - I wonder if it makes sense to include BeautifulSoup here. Overall benchmark is about article extraction, and then also html-text was added as a baseline - just to show what score a "dumb" extractor can get. So it's very similar to already existing html-text, html2text and inscripts - and they do the same thing - extract all text without trying to extract the article. So I wonder if having BeautifulSoup shows anything extra here? What do you think? I'm not against accepting it but would like to understand the motivation more.

**Comment by ldulcic** [comment]
@lopuhin I think it makes sense to add it just because BeautifulSoup is very popular. Lot of people who need to extract text from html will probably try with BeautifulSoup first. I know I was wondering what's BeautifulSoup's score on this benchmark when I looked at the table for the first time. html-text, html2text and inscriptis are very similar but are not as popular.

Basically, the only reason is that most of the "Python folks" are familiar with BeautifulSoup. What do you think?

**Comment by lopuhin** [comment]
> Lot of people who need to extract text from html will probably try with BeautifulSoup first. I know I was wondering what's BeautifulSoup's score on this benchmark when I looked at the table for the first time.

This makes a lot of sense, thanks @ldulcic :+1: 
I'm +1 to include this, do you mind resolving the conflicts? Or I can do that during the merge.

**Comment by ldulcic** [comment]
@lopuhin give me a second to resolve them

**Comment by ldulcic** [comment]
@lopuhin Done :)

**Review by lopuhin — APPROVED** [review]
Thanks @ldulcic :+1:

**Pull request merged**
